# coding: utf-8

"""
    ABIS REST API

    Innovatrics ABIS proprietary REST API

    The version of the OpenAPI document: 6.62.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr, field_validator
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CandidateIrisPartialScore(BaseModel):
    """
    CandidateIrisPartialScore
    """ # noqa: E501
    probe_position: Optional[StrictStr] = Field(default=None, alias="probePosition")
    reference_position: Optional[StrictStr] = Field(default=None, alias="referencePosition")
    score: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["probePosition", "referencePosition", "score"]

    @field_validator('probe_position')
    def probe_position_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('UNKNOWN_IRIS', 'LEFT', 'RIGHT'):
            raise ValueError("must be one of enum values ('UNKNOWN_IRIS', 'LEFT', 'RIGHT')")
        return value

    @field_validator('reference_position')
    def reference_position_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('UNKNOWN_IRIS', 'LEFT', 'RIGHT'):
            raise ValueError("must be one of enum values ('UNKNOWN_IRIS', 'LEFT', 'RIGHT')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CandidateIrisPartialScore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CandidateIrisPartialScore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "probePosition": obj.get("probePosition"),
            "referencePosition": obj.get("referencePosition"),
            "score": obj.get("score")
        })
        return _obj


