# coding: utf-8

"""
    ABIS REST API

    Innovatrics ABIS proprietary REST API

    The version of the OpenAPI document: 6.62.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FaceICAOAttributes(BaseModel):
    """
    FaceICAOAttributes
    """ # noqa: E501
    icao_bg_uniformity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoBgUniformity")
    icao_bg_uniformity_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoBgUniformityMax")
    icao_bg_uniformity_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoBgUniformityMin")
    icao_brightness: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoBrightness")
    icao_brightness_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoBrightnessMax")
    icao_brightness_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoBrightnessMin")
    icao_color_profile: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoColorProfile")
    icao_color_profile_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoColorProfileMax")
    icao_color_profile_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoColorProfileMin")
    icao_compilance: Optional[StrictInt] = Field(default=None, alias="icaoCompilance")
    icao_contrast: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoContrast")
    icao_contrast_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoContrastMax")
    icao_contrast_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoContrastMin")
    icao_eye_distance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoEyeDistance")
    icao_eye_distance_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoEyeDistanceMax")
    icao_eye_distance_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoEyeDistanceMin")
    icao_eye_gaze: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoEyeGaze")
    icao_eye_gaze_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoEyeGazeMax")
    icao_eye_gaze_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoEyeGazeMin")
    icao_glasses: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoGlasses")
    icao_glasses_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoGlassesMax")
    icao_glasses_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoGlassesMin")
    icao_glasses_status_mode: Optional[StrictStr] = Field(default=None, alias="icaoGlassesStatusMode")
    icao_heavy_frame: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoHeavyFrame")
    icao_heavy_frame_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoHeavyFrameMax")
    icao_heavy_frame_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoHeavyFrameMin")
    icao_horiz_nose_root_pos: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoHorizNoseRootPos")
    icao_horiz_nose_root_pos_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoHorizNoseRootPosMax")
    icao_horiz_nose_root_pos_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoHorizNoseRootPosMin")
    icao_left_eye_status: Optional[StrictStr] = Field(default=None, alias="icaoLeftEyeStatus")
    icao_left_eye_status_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoLeftEyeStatusMax")
    icao_left_eye_status_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoLeftEyeStatusMin")
    icao_left_eye_status_mode: Optional[StrictStr] = Field(default=None, alias="icaoLeftEyeStatusMode")
    icao_mouth_status: Optional[StrictStr] = Field(default=None, alias="icaoMouthStatus")
    icao_mouth_status_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoMouthStatusMax")
    icao_mouth_status_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoMouthStatusMin")
    icao_mouth_status_mode: Optional[StrictStr] = Field(default=None, alias="icaoMouthStatusMode")
    icao_multiple_faces: Optional[StrictInt] = Field(default=None, alias="icaoMultipleFaces")
    icao_nose_shadow: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoNoseShadow")
    icao_nose_shadow_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoNoseShadowMax")
    icao_nose_shadow_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoNoseShadowMin")
    icao_pitch_angle: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoPitchAngle")
    icao_pitch_angle_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoPitchAngleMax")
    icao_pitch_angle_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoPitchAngleMin")
    icao_rect_width: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRectWidth")
    icao_rect_width_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRectWidthMax")
    icao_rect_width_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRectWidthMin")
    icao_red_eye_left: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRedEyeLeft")
    icao_red_eye_left_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRedEyeLeftMax")
    icao_red_eye_left_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRedEyeLeftMin")
    icao_red_eye_right: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRedEyeRight")
    icao_red_eye_right_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRedEyeRightMax")
    icao_red_eye_right_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRedEyeRightMin")
    icao_right_eye_status: Optional[StrictStr] = Field(default=None, alias="icaoRightEyeStatus")
    icao_right_eye_status_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRightEyeStatusMax")
    icao_right_eye_status_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRightEyeStatusMin")
    icao_right_eye_status_mode: Optional[StrictStr] = Field(default=None, alias="icaoRightEyeStatusMode")
    icao_roll_angle: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRollAngle")
    icao_roll_angle_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRollAngleMax")
    icao_roll_angle_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoRollAngleMin")
    icao_shadow: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoShadow")
    icao_shadow_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoShadowMax")
    icao_shadow_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoShadowMin")
    icao_sharpness: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoSharpness")
    icao_sharpness_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoSharpnessMax")
    icao_sharpness_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoSharpnessMin")
    icao_specularity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoSpecularity")
    icao_specularity_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoSpecularityMax")
    icao_specularity_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoSpecularityMin")
    icao_vertical_eye_position: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoVerticalEyePosition")
    icao_vertical_eye_position_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoVerticalEyePositionMax")
    icao_vertical_eye_position_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoVerticalEyePositionMin")
    icao_yaw_angle: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoYawAngle")
    icao_yaw_angle_max: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoYawAngleMax")
    icao_yaw_angle_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="icaoYawAngleMin")
    __properties: ClassVar[List[str]] = ["icaoBgUniformity", "icaoBgUniformityMax", "icaoBgUniformityMin", "icaoBrightness", "icaoBrightnessMax", "icaoBrightnessMin", "icaoColorProfile", "icaoColorProfileMax", "icaoColorProfileMin", "icaoCompilance", "icaoContrast", "icaoContrastMax", "icaoContrastMin", "icaoEyeDistance", "icaoEyeDistanceMax", "icaoEyeDistanceMin", "icaoEyeGaze", "icaoEyeGazeMax", "icaoEyeGazeMin", "icaoGlasses", "icaoGlassesMax", "icaoGlassesMin", "icaoGlassesStatusMode", "icaoHeavyFrame", "icaoHeavyFrameMax", "icaoHeavyFrameMin", "icaoHorizNoseRootPos", "icaoHorizNoseRootPosMax", "icaoHorizNoseRootPosMin", "icaoLeftEyeStatus", "icaoLeftEyeStatusMax", "icaoLeftEyeStatusMin", "icaoLeftEyeStatusMode", "icaoMouthStatus", "icaoMouthStatusMax", "icaoMouthStatusMin", "icaoMouthStatusMode", "icaoMultipleFaces", "icaoNoseShadow", "icaoNoseShadowMax", "icaoNoseShadowMin", "icaoPitchAngle", "icaoPitchAngleMax", "icaoPitchAngleMin", "icaoRectWidth", "icaoRectWidthMax", "icaoRectWidthMin", "icaoRedEyeLeft", "icaoRedEyeLeftMax", "icaoRedEyeLeftMin", "icaoRedEyeRight", "icaoRedEyeRightMax", "icaoRedEyeRightMin", "icaoRightEyeStatus", "icaoRightEyeStatusMax", "icaoRightEyeStatusMin", "icaoRightEyeStatusMode", "icaoRollAngle", "icaoRollAngleMax", "icaoRollAngleMin", "icaoShadow", "icaoShadowMax", "icaoShadowMin", "icaoSharpness", "icaoSharpnessMax", "icaoSharpnessMin", "icaoSpecularity", "icaoSpecularityMax", "icaoSpecularityMin", "icaoVerticalEyePosition", "icaoVerticalEyePositionMax", "icaoVerticalEyePositionMin", "icaoYawAngle", "icaoYawAngleMax", "icaoYawAngleMin"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FaceICAOAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FaceICAOAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "icaoBgUniformity": obj.get("icaoBgUniformity"),
            "icaoBgUniformityMax": obj.get("icaoBgUniformityMax"),
            "icaoBgUniformityMin": obj.get("icaoBgUniformityMin"),
            "icaoBrightness": obj.get("icaoBrightness"),
            "icaoBrightnessMax": obj.get("icaoBrightnessMax"),
            "icaoBrightnessMin": obj.get("icaoBrightnessMin"),
            "icaoColorProfile": obj.get("icaoColorProfile"),
            "icaoColorProfileMax": obj.get("icaoColorProfileMax"),
            "icaoColorProfileMin": obj.get("icaoColorProfileMin"),
            "icaoCompilance": obj.get("icaoCompilance"),
            "icaoContrast": obj.get("icaoContrast"),
            "icaoContrastMax": obj.get("icaoContrastMax"),
            "icaoContrastMin": obj.get("icaoContrastMin"),
            "icaoEyeDistance": obj.get("icaoEyeDistance"),
            "icaoEyeDistanceMax": obj.get("icaoEyeDistanceMax"),
            "icaoEyeDistanceMin": obj.get("icaoEyeDistanceMin"),
            "icaoEyeGaze": obj.get("icaoEyeGaze"),
            "icaoEyeGazeMax": obj.get("icaoEyeGazeMax"),
            "icaoEyeGazeMin": obj.get("icaoEyeGazeMin"),
            "icaoGlasses": obj.get("icaoGlasses"),
            "icaoGlassesMax": obj.get("icaoGlassesMax"),
            "icaoGlassesMin": obj.get("icaoGlassesMin"),
            "icaoGlassesStatusMode": obj.get("icaoGlassesStatusMode"),
            "icaoHeavyFrame": obj.get("icaoHeavyFrame"),
            "icaoHeavyFrameMax": obj.get("icaoHeavyFrameMax"),
            "icaoHeavyFrameMin": obj.get("icaoHeavyFrameMin"),
            "icaoHorizNoseRootPos": obj.get("icaoHorizNoseRootPos"),
            "icaoHorizNoseRootPosMax": obj.get("icaoHorizNoseRootPosMax"),
            "icaoHorizNoseRootPosMin": obj.get("icaoHorizNoseRootPosMin"),
            "icaoLeftEyeStatus": obj.get("icaoLeftEyeStatus"),
            "icaoLeftEyeStatusMax": obj.get("icaoLeftEyeStatusMax"),
            "icaoLeftEyeStatusMin": obj.get("icaoLeftEyeStatusMin"),
            "icaoLeftEyeStatusMode": obj.get("icaoLeftEyeStatusMode"),
            "icaoMouthStatus": obj.get("icaoMouthStatus"),
            "icaoMouthStatusMax": obj.get("icaoMouthStatusMax"),
            "icaoMouthStatusMin": obj.get("icaoMouthStatusMin"),
            "icaoMouthStatusMode": obj.get("icaoMouthStatusMode"),
            "icaoMultipleFaces": obj.get("icaoMultipleFaces"),
            "icaoNoseShadow": obj.get("icaoNoseShadow"),
            "icaoNoseShadowMax": obj.get("icaoNoseShadowMax"),
            "icaoNoseShadowMin": obj.get("icaoNoseShadowMin"),
            "icaoPitchAngle": obj.get("icaoPitchAngle"),
            "icaoPitchAngleMax": obj.get("icaoPitchAngleMax"),
            "icaoPitchAngleMin": obj.get("icaoPitchAngleMin"),
            "icaoRectWidth": obj.get("icaoRectWidth"),
            "icaoRectWidthMax": obj.get("icaoRectWidthMax"),
            "icaoRectWidthMin": obj.get("icaoRectWidthMin"),
            "icaoRedEyeLeft": obj.get("icaoRedEyeLeft"),
            "icaoRedEyeLeftMax": obj.get("icaoRedEyeLeftMax"),
            "icaoRedEyeLeftMin": obj.get("icaoRedEyeLeftMin"),
            "icaoRedEyeRight": obj.get("icaoRedEyeRight"),
            "icaoRedEyeRightMax": obj.get("icaoRedEyeRightMax"),
            "icaoRedEyeRightMin": obj.get("icaoRedEyeRightMin"),
            "icaoRightEyeStatus": obj.get("icaoRightEyeStatus"),
            "icaoRightEyeStatusMax": obj.get("icaoRightEyeStatusMax"),
            "icaoRightEyeStatusMin": obj.get("icaoRightEyeStatusMin"),
            "icaoRightEyeStatusMode": obj.get("icaoRightEyeStatusMode"),
            "icaoRollAngle": obj.get("icaoRollAngle"),
            "icaoRollAngleMax": obj.get("icaoRollAngleMax"),
            "icaoRollAngleMin": obj.get("icaoRollAngleMin"),
            "icaoShadow": obj.get("icaoShadow"),
            "icaoShadowMax": obj.get("icaoShadowMax"),
            "icaoShadowMin": obj.get("icaoShadowMin"),
            "icaoSharpness": obj.get("icaoSharpness"),
            "icaoSharpnessMax": obj.get("icaoSharpnessMax"),
            "icaoSharpnessMin": obj.get("icaoSharpnessMin"),
            "icaoSpecularity": obj.get("icaoSpecularity"),
            "icaoSpecularityMax": obj.get("icaoSpecularityMax"),
            "icaoSpecularityMin": obj.get("icaoSpecularityMin"),
            "icaoVerticalEyePosition": obj.get("icaoVerticalEyePosition"),
            "icaoVerticalEyePositionMax": obj.get("icaoVerticalEyePositionMax"),
            "icaoVerticalEyePositionMin": obj.get("icaoVerticalEyePositionMin"),
            "icaoYawAngle": obj.get("icaoYawAngle"),
            "icaoYawAngleMax": obj.get("icaoYawAngleMax"),
            "icaoYawAngleMin": obj.get("icaoYawAngleMin")
        })
        return _obj


