# coding: utf-8

"""
    ABIS REST API

    Innovatrics ABIS proprietary REST API

    The version of the OpenAPI document: 6.62.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from abis.rest.client.models.adjudication_report import AdjudicationReport
from abis.rest.client.models.resolve_hitlist_response_data import ResolveHitlistResponseData
from abis.rest.client.models.resolve_queue_action import ResolveQueueAction
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class HitlistActionResponse(BaseModel):
    """
    HitlistActionResponse
    """ # noqa: E501
    action: Optional[ResolveQueueAction] = None
    adjudication_report: Optional[AdjudicationReport] = Field(default=None, alias="adjudicationReport")
    after: Optional[ResolveHitlistResponseData] = None
    before: Optional[ResolveHitlistResponseData] = None
    performed_at: Optional[datetime] = Field(default=None, alias="performedAt")
    performed_by: Optional[StrictStr] = Field(default=None, alias="performedBy")
    __properties: ClassVar[List[str]] = ["action", "adjudicationReport", "after", "before", "performedAt", "performedBy"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HitlistActionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of action
        if self.action:
            _dict['action'] = self.action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of adjudication_report
        if self.adjudication_report:
            _dict['adjudicationReport'] = self.adjudication_report.to_dict()
        # override the default output from pydantic by calling `to_dict()` of after
        if self.after:
            _dict['after'] = self.after.to_dict()
        # override the default output from pydantic by calling `to_dict()` of before
        if self.before:
            _dict['before'] = self.before.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of HitlistActionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": ResolveQueueAction.from_dict(obj.get("action")) if obj.get("action") is not None else None,
            "adjudicationReport": AdjudicationReport.from_dict(obj.get("adjudicationReport")) if obj.get("adjudicationReport") is not None else None,
            "after": ResolveHitlistResponseData.from_dict(obj.get("after")) if obj.get("after") is not None else None,
            "before": ResolveHitlistResponseData.from_dict(obj.get("before")) if obj.get("before") is not None else None,
            "performedAt": obj.get("performedAt"),
            "performedBy": obj.get("performedBy")
        })
        return _obj


