# coding: utf-8

"""
    ABIS REST API

    Innovatrics ABIS proprietary REST API

    The version of the OpenAPI document: 6.62.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from abis.rest.client.models.roi_point import ROIPoint
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RegionOfInterest(BaseModel):
    """
    RegionOfInterest
    """ # noqa: E501
    bottom_left: Optional[ROIPoint] = Field(default=None, alias="bottomLeft")
    bottom_right: Optional[ROIPoint] = Field(default=None, alias="bottomRight")
    top_left: Optional[ROIPoint] = Field(default=None, alias="topLeft")
    top_right: Optional[ROIPoint] = Field(default=None, alias="topRight")
    __properties: ClassVar[List[str]] = ["bottomLeft", "bottomRight", "topLeft", "topRight"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RegionOfInterest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of bottom_left
        if self.bottom_left:
            _dict['bottomLeft'] = self.bottom_left.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bottom_right
        if self.bottom_right:
            _dict['bottomRight'] = self.bottom_right.to_dict()
        # override the default output from pydantic by calling `to_dict()` of top_left
        if self.top_left:
            _dict['topLeft'] = self.top_left.to_dict()
        # override the default output from pydantic by calling `to_dict()` of top_right
        if self.top_right:
            _dict['topRight'] = self.top_right.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RegionOfInterest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bottomLeft": ROIPoint.from_dict(obj.get("bottomLeft")) if obj.get("bottomLeft") is not None else None,
            "bottomRight": ROIPoint.from_dict(obj.get("bottomRight")) if obj.get("bottomRight") is not None else None,
            "topLeft": ROIPoint.from_dict(obj.get("topLeft")) if obj.get("topLeft") is not None else None,
            "topRight": ROIPoint.from_dict(obj.get("topRight")) if obj.get("topRight") is not None else None
        })
        return _obj


