# coding: utf-8

"""
    ABIS REST API

    Innovatrics ABIS proprietary REST API

    The version of the OpenAPI document: 6.62.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from pydantic import Field
from abis.rest.client.models.resolve_queue import ResolveQueue
from abis.rest.client.models.workflows_biometric_individual import WorkflowsBiometricIndividual
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ResolveHitlistResponseData(BaseModel):
    """
    ResolveHitlistResponseData
    """ # noqa: E501
    probe_biometric_individual: Optional[WorkflowsBiometricIndividual] = Field(default=None, alias="probeBiometricIndividual")
    reference_biometric_individual: Optional[WorkflowsBiometricIndividual] = Field(default=None, alias="referenceBiometricIndividual")
    resolve_queue: Optional[ResolveQueue] = Field(default=None, alias="resolveQueue")
    __properties: ClassVar[List[str]] = ["probeBiometricIndividual", "referenceBiometricIndividual", "resolveQueue"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ResolveHitlistResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of probe_biometric_individual
        if self.probe_biometric_individual:
            _dict['probeBiometricIndividual'] = self.probe_biometric_individual.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reference_biometric_individual
        if self.reference_biometric_individual:
            _dict['referenceBiometricIndividual'] = self.reference_biometric_individual.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resolve_queue
        if self.resolve_queue:
            _dict['resolveQueue'] = self.resolve_queue.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ResolveHitlistResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "probeBiometricIndividual": WorkflowsBiometricIndividual.from_dict(obj.get("probeBiometricIndividual")) if obj.get("probeBiometricIndividual") is not None else None,
            "referenceBiometricIndividual": WorkflowsBiometricIndividual.from_dict(obj.get("referenceBiometricIndividual")) if obj.get("referenceBiometricIndividual") is not None else None,
            "resolveQueue": ResolveQueue.from_dict(obj.get("resolveQueue")) if obj.get("resolveQueue") is not None else None
        })
        return _obj


