# coding: utf-8

"""
    ABIS REST API

    Innovatrics ABIS proprietary REST API

    The version of the OpenAPI document: 6.62.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class TransactionType(str, Enum):
    """
    Transaction type.
    """

    """
    allowed enum values
    """
    UNSPECIFIED = 'unspecified'
    CAR = 'car'
    CNA = 'cna'
    FIS = 'fis'
    MAP = 'map'
    ATP = 'atp'
    APC = 'apc'
    UPR = 'upr'
    DFP = 'dfp'
    LFS = 'lfs'
    LFIS = 'lfis'
    USA = 'usa'
    USR = 'usr'
    TPIS = 'tpis'
    LFFS = 'lffs'
    CPS = 'cps'
    NPS = 'nps'
    MPS = 'mps'
    FRS = 'frs'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransactionType from a JSON string"""
        return cls(json.loads(json_str))


