# coding: utf-8

"""
    ABIS REST API

    Innovatrics ABIS proprietary REST API

    The version of the OpenAPI document: 6.62.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from abis.rest.client.models.applicant_custom_details import ApplicantCustomDetails
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UpdateFieldsRequest(BaseModel):
    """
    UpdateFieldsRequest
    """ # noqa: E501
    category: Optional[StrictStr] = None
    custom_details: Optional[ApplicantCustomDetails] = Field(default=None, alias="customDetails")
    enrolled_at: Optional[datetime] = Field(default=None, description="A date-time format in the ISO-8601 calendar system", alias="enrolledAt")
    enrolled_by: Optional[StrictStr] = Field(default=None, alias="enrolledBy")
    enrollment_device: Optional[StrictStr] = Field(default=None, alias="enrollmentDevice")
    exported_at: Optional[datetime] = Field(default=None, description="A date-time format in the ISO-8601 calendar system", alias="exportedAt")
    exported_by: Optional[StrictStr] = Field(default=None, alias="exportedBy")
    __properties: ClassVar[List[str]] = ["category", "customDetails", "enrolledAt", "enrolledBy", "enrollmentDevice", "exportedAt", "exportedBy"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpdateFieldsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of custom_details
        if self.custom_details:
            _dict['customDetails'] = self.custom_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UpdateFieldsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "category": obj.get("category"),
            "customDetails": ApplicantCustomDetails.from_dict(obj.get("customDetails")) if obj.get("customDetails") is not None else None,
            "enrolledAt": obj.get("enrolledAt"),
            "enrolledBy": obj.get("enrolledBy"),
            "enrollmentDevice": obj.get("enrollmentDevice"),
            "exportedAt": obj.get("exportedAt"),
            "exportedBy": obj.get("exportedBy")
        })
        return _obj


